name: Action Command Simple2

on:
  pull_request: [assigned, opened, reopened, closed]
jobs:
    run-github-action:
        runs-on: ubuntu-latest
        steps:
          - name: list Files
            run: |
              pwd
              ls
         # - name: Checkout
         #   uses: actions/checkout@v1
         # - name: list Files after checkout
         #   run: |
         #     pwd
        #    ls   
        
                 
