name: Action Command Simple2

on: [push]
jobs:
    run-github-action:
        runs-on: ubuntu-latest
        steps:
          - name: list Files
            run: |
              pwd
              ls
          - name: Checkout
            uses: actions/checkout@v1
