name: Shell Command only on pull

on: [push]
jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: print a string
            run: echo "Hi My Name is Vipin"
          - name: multi line script
            run: |
              node -v
              npm -v
              hostname
          - name: python command
            run: |
              import platform
              print
              (platform.processor())
            shell: python  
    run-win-cmd:
        runs-on: windows-latest
        needs: ['run-shell-command']
        steps:
          - name: On Powershell
            run: Get-Location
          - name:  Directory Bash
            run: pwd
            shell: bash   